"""Initial schema migration

Revision ID: 4a09b9119748
Revises: 
Create Date: 2026-09-10 12:10:27.207939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a09b9119748'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mission_title', sa.String(length=255), nullable=False),
    sa.Column('mission_description', sa.Text(), nullable=False),
    sa.Column('translation_philosophy', sa.Text(), nullable=False),
    sa.Column('director_name', sa.String(length=128), nullable=False),
    sa.Column('director_role', sa.String(length=255), nullable=False),
    sa.Column('director_bio', sa.Text(), nullable=False),
    sa.Column('director_image', sa.String(length=512), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('collaborators',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('joint_focus', sa.JSON(), nullable=True),
    sa.Column('key_contacts', sa.JSON(), nullable=True),
    sa.Column('active_trials', sa.JSON(), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_inquiries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('interest_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('icon_name', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('hero_badge', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=255), nullable=False),
    sa.Column('hero_highlight', sa.String(length=255), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('callout_title', sa.String(length=255), nullable=False),
    sa.Column('callout_subtitle', sa.Text(), nullable=False),
    sa.Column('callout_button_text', sa.String(length=128), nullable=False),
    sa.Column('callout_button_link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('link_text', sa.String(length=128), nullable=True),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('journal', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('doi_url', sa.String(length=512), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('code_url', sa.String(length=512), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('bibtex', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_pillars',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('grant_number', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lab_name', sa.String(length=128), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=128), nullable=False),
    sa.Column('contact_phone', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('room_location', sa.String(length=255), nullable=False),
    sa.Column('visiting_hours', sa.String(length=255), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('credentials', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('detailed_bio', sa.Text(), nullable=True),
    sa.Column('lab_role_detail', sa.Text(), nullable=True),
    sa.Column('focus', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('contributions', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('publications', sa.JSON(), nullable=True),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('scholar_url', sa.String(length=512), nullable=True),
    sa.Column('orcid_url', sa.String(length=512), nullable=True),
    sa.Column('research_gate_url', sa.String(length=512), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('twitter_url', sa.String(length=512), nullable=True),
    sa.Column('instagram_url', sa.String(length=512), nullable=True),
    sa.Column('show_email', sa.Boolean(), nullable=True),
    sa.Column('show_social_links', sa.Boolean(), nullable=True),
    sa.Column('show_publications', sa.Boolean(), nullable=True),
    sa.Column('show_projects', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_sessions')
    op.drop_table('team_members')
    op.drop_table('site_settings')
    op.drop_table('research_pillars')
    op.drop_table('publications')
    op.drop_table('news_items')
    op.drop_table('homepage_config')
    op.drop_table('gallery_items')
    op.drop_table('facilities')
    op.drop_table('contact_inquiries')
    op.drop_table('collaborators')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    op.drop_table('about_config')
    # ### end Alembic commands ###
