import Link from "next/link";
import { ArrowRight, ArrowUpRight, Building2, ChevronRight, Users } from "lucide-react";
import { HeroCarousel } from "@/components/hero-carousel";
import { facilities, newsItems, publications, researchAreas, teamMembers } from "@/lib/content";

export function HomePage() {
  return <>
    <section className="border-b border-slate-200 bg-white"><div className="container-wide flex min-h-12 items-center justify-between gap-4 py-3 text-sm"><p className="text-slate-700"><span className="mr-2 font-bold text-maroon-800">Announcement</span> The laboratory is accepting research inquiries for the coming academic year.</p><Link href="/contact" className="focus-ring hidden shrink-0 items-center gap-2 text-xs font-bold uppercase tracking-wider text-maroon-800 sm:inline-flex">Get in touch <ArrowRight size={14} /></Link></div></section>

    <section className="container-wide py-6 sm:py-10"><HeroCarousel /></section>

    <section className="border-y border-slate-200 bg-white"><div className="container-wide grid gap-12 py-20 sm:py-24 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-maroon-700">Research at MINDH</p><h2 className="mt-5 max-w-md text-4xl font-extrabold leading-[1.08] tracking-[-0.03em] text-slate-950 sm:text-5xl">Questions before solutions.</h2><Link href="/research" className="focus-ring mt-8 inline-flex items-center gap-2 text-sm font-bold text-maroon-800">Explore the research program <ArrowRight size={15} /></Link></div><div className="divide-y divide-slate-200 border-y border-slate-200">{researchAreas.map((area, index) => <Link key={area.id} href={`/research#${area.slug}`} className="focus-ring group grid gap-5 py-7 sm:grid-cols-[56px_1fr_auto] sm:items-start"><span className="text-xs font-bold tracking-[0.2em] text-maroon-700">0{index + 1}</span><span><span className="block text-2xl font-bold tracking-tight text-slate-950 group-hover:text-maroon-800">{area.title}</span><span className="mt-2 block max-w-xl text-sm leading-6 text-slate-600">{area.summary}</span></span><ChevronRight size={18} className="hidden text-maroon-700 transition-transform group-hover:translate-x-1 sm:mt-1 sm:block" /></Link>)}</div></div></section>

    <section className="container-wide border-b border-slate-200 py-20 sm:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-maroon-700">Selected work</p><h2 className="mt-4 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">From the publication record</h2></div><Link href="/publications" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-maroon-800">All publications <ArrowUpRight size={16} /></Link></div><div className="mt-10 grid gap-4 lg:grid-cols-2">{publications.slice(0, 2).map((publication) => <article key={publication.id} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-wider text-maroon-700"><span>{publication.type}</span><span>{publication.year}</span></div><h3 className="mt-12 text-xl font-bold leading-snug text-slate-950">{publication.title}</h3><p className="mt-3 text-sm text-slate-500">{publication.venue}</p><p className="mt-5 text-sm leading-7 text-slate-600">{publication.abstract}</p></article>)}</div></section>

    <section className="bg-maroon-50"><div className="container-wide grid gap-12 py-20 sm:py-24 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-maroon-700">Research environments</p><h2 className="mt-5 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Places to observe, build, and learn.</h2><p className="mt-5 max-w-md text-base leading-7 text-slate-600">Our facilities support collaborative investigation across data, signals, and digital systems.</p><Link href="/facilities" className="focus-ring mt-7 inline-flex items-center gap-2 rounded-xl bg-maroon-800 px-5 py-3 text-sm font-bold text-white hover:bg-maroon-900">Explore facilities <Building2 size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2">{facilities.map((facility) => <article key={facility.id} className="rounded-2xl border border-maroon-100 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-maroon-700">{facility.category}</p><h3 className="mt-10 text-xl font-bold text-slate-950">{facility.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{facility.summary}</p></article>)}</div></div></section>

    <section className="container-wide border-b border-slate-200 py-20 sm:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-maroon-700">News &amp; events</p><h2 className="mt-4 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">From the laboratory</h2></div><Link href="/news" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-maroon-800">View all news <ArrowUpRight size={16} /></Link></div><div className="mt-10 grid gap-4 md:grid-cols-2">{newsItems.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-wider text-maroon-700"><span>{item.category}</span><time dateTime={item.date}>{item.date}</time></div><h3 className="mt-12 text-xl font-bold text-slate-950">{item.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{item.summary}</p></article>)}</div></section>

    <section id="group" className="container-wide py-20 sm:py-24"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-maroon-700">Research group</p><h2 className="mt-5 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">People who make the work possible.</h2></div><p className="max-w-2xl text-base leading-7 text-slate-600">The group brings together clinical, computational, and design perspectives around shared research questions.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{teamMembers.map((member) => <article key={member.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid size-12 place-items-center rounded-full bg-maroon-100 text-sm font-bold text-maroon-800">{member.initials}</div><h3 className="mt-8 text-xl font-bold text-slate-950">{member.name}</h3><p className="mt-1 text-sm font-semibold text-maroon-700">{member.role}</p><p className="mt-4 text-sm leading-6 text-slate-600">{member.summary}</p></article>)}</div><Link href="/contact" className="focus-ring mt-8 inline-flex items-center gap-2 text-sm font-bold text-maroon-800">Work with the group <Users size={16} /></Link></section>

    <section className="container-wide pb-24 sm:pb-28"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-r from-maroon-900 via-[#8d3048] to-[#eadfe1] p-8 shadow-[0_24px_60px_-28px_rgba(91,16,35,.55)] sm:p-12 lg:p-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/75">Connect</p><h2 className="mt-5 max-w-3xl text-4xl font-extrabold leading-tight tracking-[-0.02em] text-white sm:text-5xl">Have a question about the work?</h2><p className="mt-5 max-w-2xl text-base leading-7 text-white/80">Learn more about our research and how to contact the laboratory.</p><Link href="/contact" className="focus-ring mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-bold text-maroon-900 hover:bg-rose-50">Contact the laboratory <ArrowRight size={16} /></Link></div></div></section>
  </>;
}
